services:
  opencode:
    container_name: opencode
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        DOCKER_GID: ${DOCKER_GID:-1001}
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.opencode/config:/home/opencode/.config/opencode
      - ./.opencode/share:/home/opencode/.local/share/opencode
    ports:
      - "4096:4096"
