services:
  opencode:
    container_name: opencode
    build:
      context: ./docker
      dockerfile: ${OPENCODE_DOCKERFILE:-Dockerfile}
      args:
        USER_UID: ${USER_UID:?USER_UID is not set. Run via make commands}
        USER_GID: ${USER_GID:?USER_GID is not set. Run via make commands}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.opencode/config:/home/opencode/.config/opencode
      - opencode_share:/home/opencode/.local/share/opencode
    environment:
      OPENCODE_DISABLE_AUTOUPDATE: true
    ports:
      - "4096:4096"

volumes:
  opencode_share:
